apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-config
  name: k8s-config
spec:
  type: NodePort
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 32222
  selector:
    app: k8s-config